# Generated by Django 3.2.7 on 2021-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('domain', models.CharField(max_length=127, verbose_name='domain')),
                ('first_name', models.CharField(blank=True, max_length=127, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=127, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=127, verbose_name='role')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
        ),
    ]
